blog/config/routes.rb
Blog::Application.routes.draw do
  devise_for :admins

  resources :post_tag_relations

  resources :posts do
    resources :comments
    resources :tags
  end

  resources :comments

  resources :tags do
    resources :posts
  end

  resources :images

root :to => "posts#index"

end

blog/app/models/post_tag_relation.rb
class PostTagRelation < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

blog/app/controllers/post_tag_relations_controller.rb
class PostTagRelationsController < ApplicationController
  # GET /post_tag_relations
  # GET /post_tag_relations.xml
  def index
    @post_tag_relations = PostTagRelation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @post_tag_relations }
    end
  end

  # GET /post_tag_relations/1
  # GET /post_tag_relations/1.xml
  def show
    @post_tag_relation = PostTagRelation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post_tag_relation }
    end
  end

  # GET /post_tag_relations/new
  # GET /post_tag_relations/new.xml
  def new
    @post_tag_relation = PostTagRelation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post_tag_relation }
    end
  end

  # GET /post_tag_relations/1/edit
  def edit
    @post_tag_relation = PostTagRelation.find(params[:id])
  end

  # POST /post_tag_relations
  # POST /post_tag_relations.xml
  def create
    @post_tag_relation = PostTagRelation.new(params[:post_tag_relation])

    respond_to do |format|
      if @post_tag_relation.save
        format.html { redirect_to(@post_tag_relation, :notice => 'Post tag relation was successfully created.') }
        format.xml  { render :xml => @post_tag_relation, :status => :created, :location => @post_tag_relation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post_tag_relation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /post_tag_relations/1
  # PUT /post_tag_relations/1.xml
  def update
    @post_tag_relation = PostTagRelation.find(params[:id])

    respond_to do |format|
      if @post_tag_relation.update_attributes(params[:post_tag_relation])
        format.html { redirect_to(@post_tag_relation, :notice => 'Post tag relation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post_tag_relation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /post_tag_relations/1
  # DELETE /post_tag_relations/1.xml
  def destroy
    @post_tag_relation = PostTagRelation.find(params[:id])
    @post_tag_relation.destroy

    respond_to do |format|
      format.html { redirect_to(post_tag_relations_url) }
      format.xml  { head :ok }
    end
  end
end

blog/app/helpers/post_tag_relations_helper.rb
module PostTagRelationsHelper
end

blog/app/views/post_tag_relations/_form.html.erb
<%= form_for(@post_tag_relation) do |f| %>
  <% if @post_tag_relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_tag_relation.errors.count, "error") %> prohibited this post_tag_relation from being saved:</h2>

      <ul>
      <% @post_tag_relation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/post_tag_relations/edit.html.erb
<h1>Editing post_tag_relation</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_tag_relation %> |
<%= link_to 'Back', post_tag_relations_path %>

blog/app/views/post_tag_relations/index.html.erb
<h1>Listing post_tag_relations</h1>

<table>
  <tr>
    <th>Tag</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post_tag_relations.each do |post_tag_relation| %>
  <tr>
    <td><%= post_tag_relation.tag %></td>
    <td><%= post_tag_relation.post %></td>
    <td><%= link_to 'Show', post_tag_relation %></td>
    <td><%= link_to 'Edit', edit_post_tag_relation_path(post_tag_relation) %></td>
    <td><%= link_to 'Destroy', post_tag_relation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post tag relation', new_post_tag_relation_path %>

blog/app/views/post_tag_relations/new.html.erb
<h1>New post_tag_relation</h1>

<%= render 'form' %>

<%= link_to 'Back', post_tag_relations_path %>

blog/app/views/post_tag_relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tag:</b>
  <%= @post_tag_relation.tag %>
</p>

<p>
  <b>Post:</b>
  <%= @post_tag_relation.post %>
</p>


<%= link_to 'Edit', edit_post_tag_relation_path(@post_tag_relation) %> |
<%= link_to 'Back', post_tag_relations_path %>