blog/config/routes.rb
Blog::Application.routes.draw do
  devise_for :admins

  resources :post_tag_relations

  resources :posts do
    resources :comments
    resources :tags
  end

  resources :comments

  resources :tags do
    resources :posts
  end

  resources :images

root :to => "posts#index"

end

blog/app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, :dependent => :destroy
    has_many :post_tag_relations, :dependent => :destroy
    has_many :tags, :through => :post_tag_relations
    has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "100x100" }

end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:show, :index] 
  # GET /posts
  # GET /posts.xml

  layout :set_layout

  def index
    @posts = Post.all.reverse
    @tags = Tag.all

  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new
    @tags = Tag.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @tags = Tag.all
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.create(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    params[:post][:tag_ids] ||= []
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_url
  end

  private
  def set_layout
    case params[:action]
    when "index"
        "application_img"
    else
        "application"
    end
  end
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/posts/_form.html.erb
<% form_for :post, @post, :url => posts_path, :html => { :multipart => true } do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

  <% @tags.each do |tag| %>
    <%= check_box_tag "post[tag_ids][]", tag.id, @post.tags.include?(tag) %>
    <%= tag.name %>
  <% end %><br />

  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Home', posts_path %>

blog/app/views/posts/index.html.erb
|<% @tags.each do |tag| %>
    <%= link_to tag.name, tag, :class => "tag_list" %> |
<% end %>



<% @posts.each do |post| %>
  
    <h2><%=link_to post.title, post, :class => "post" %></h2>

    <p><%= post.created_at %></p>

    Tags: <% post.tags.each do |tag| %>
        <%= link_to tag.name, tag %>
    <% end %>

    <p>
    <ul class="gallery clearfix">
    <%= link_to image_tag(post.image.url(:medium), :title => post.title), post.image.url, {:rel => "prettyPhoto", :title => post.title} %>
    </ul>
    </p>

    <p><%= post.content %></p>

    <%= link_to 'More...', post %>

<% end %>


<br />

<% if admin_signed_in? %>
    <br /><br /><%= link_to 'New Post', new_post_path, :class => "post" %>
<% end %>

blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

    <h2><%= @post.title %></h2>

    <p><%= @post.created_at %></p>

    Tags: <% @post.tags.each do |tag| %>
        <%= link_to tag.name, tag %>
    <% end %>

    <p>
    <ul class="gallery clearfix">
    <%= link_to image_tag(@post.image.url(:medium), :title => @post.title), @post.image.url, {:rel => "prettyPhoto", :title => @post.title} %>
    </ul>
    </p>

    <p><%= @post.content %></p>
    <% if admin_signed_in? %>
        <%= link_to 'Edit', edit_post_path(@post) %>|
        <%= link_to 'Destroy', @post, :confirm => 'Are you sure?', :method => :delete %>
    <% end %>
<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <h3>
    <b><%= comment.author %></b> says:
  </h3>
 
  <p>
    <%= comment.content %>
  </p>
<% end %>
 
<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :content, :class => "comment"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', posts_path %>