blog/config/routes.rb
Blog::Application.routes.draw do
  devise_for :admins

  resources :post_tag_relations

  resources :posts do
    resources :comments
    resources :tags
  end

  resources :comments

  resources :tags do
    resources :posts
  end

  resources :images

root :to => "posts#index"

end

blog/app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :post_tag_relations
    has_many :posts, :through => :post_tag_relations
end

blog/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.xml

  layout :set_layout

  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to(@tag, :notice => 'Tag was successfully created.') }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end

  private
  def set_layout
    case params[:action]
    when "show"
        "application_img"
    else
        "application"
    end
  end
end

blog/app/helpers/tags_helper.rb
module TagsHelper
end

blog/app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

blog/app/views/tags/index.html.erb
<h2>Listing tags</h2>

<table>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
        <% if admin_signed_in? %>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, :confirm => 'Are you sure?', :method => :delete %></td>
        <% end %>
  </tr>
<% end %>
</table>

<br />
<% if admin_signed_in? %>
    <%= link_to 'New Tag', new_tag_path %>|
<% end %>
<%= link_to 'Home', posts_path %>

blog/app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

blog/app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <%= @tag.name %>
</h3>

<% @tag.posts.each do |post| %>
    <h2><%= post.title %></h2>

    <p><%= post.created_at %></p>

    Tags: <% post.tags.each do |tag| %>
        <%= link_to tag.name, tag %>
    <% end %>

    <p>
    <ul class="gallery clearfix">
    <%= link_to image_tag(post.image.url(:medium), :title => post.title), post.image.url, {:rel => "prettyPhoto", :title => post.title} %>
    </ul>
    </p>

    <p><%= post.content %></p>

    <%= link_to 'More...', post %>
        <% if admin_signed_in? %>
            |<%= link_to 'Edit', edit_post_path(post) %>
        <% end %><br /><br />
<% end %>

     <% if admin_signed_in? %>
        <%= link_to 'Edit', edit_tag_path(@tag) %> |
     <% end %>
<%= link_to 'All tags', tags_path %> |
<%= link_to 'Home', posts_path %>