blog/config/routes.rb
Blog::Application.routes.draw do
  devise_for :admins

  resources :post_tag_relations

  resources :posts do
    resources :comments
    resources :tags
  end

  resources :comments

  resources :tags do
    resources :posts
  end

  resources :images

root :to => "posts#index"

end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
   <div id="user_nav">
     <% if admin_signed_in? %>
       Signed in as <%= current_admin.email %>. Not you?
       <%= link_to "Sign out", destroy_admin_session_path %>
     <% else %>
       <%= link_to "Sign up", new_admin_registration_path %> or
       <%= link_to "Sign in", new_admin_session_path %>
     <% end %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
   </div> 
    <div id="main">
        <center><br /><br /><br />
            <%=link_to '[Blog]', posts_path, :class => "title" %>
            <%=link_to '[Gallery]', images_path, :class => "title" %>

            <h2> you'd better talk to me than read my blog... <br/> but you can look at some pics ;)
            <h1> </h1>
        </center>
        <%= yield %>
    </div>

</body>
</html>

blog/app/views/layouts/application_img.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body>
   <div id="user_nav">
     <% if admin_signed_in? %>
       Signed in as <%= current_admin.email %>. Not you?
       <%= link_to "Sign out", destroy_admin_session_path %>
     <% else %>
       <%= link_to "Sign up", new_admin_registration_path %> or
       <%= link_to "Sign in", new_admin_session_path %>
     <% end %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
   </div> 
    <div id="main">

        <center><br /><br /><br />
            <%=link_to '[Blog]', posts_path, :class => "title" %>
            <%=link_to '[Gallery]', images_path, :class => "title" %>
            <h2> you'd better talk to me than read my blog... <br/> but you can look at some pics ;)
            <h1> </h1>
        </center>
        <%= yield %>
    </div>

    <script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
	    $(".gallery:first a[rel^='prettyPhoto']").prettyPhoto({animationSpeed:'slow',theme:'light_square',slideshow:2000, autoplay_slideshow: false});
	    $(".gallery:gt(0) a[rel^='prettyPhoto']").prettyPhoto({animationSpeed:'fast',slideshow:10000});
	
	    $("#custom_content a[rel^='prettyPhoto']:first").prettyPhoto({
		    custom_markup: '<div id="map_canvas" style="width:260px; height:265px"></div>',
		    changepicturecallback: function(){ initialize(); }
	    });

	    $("#custom_content a[rel^='prettyPhoto']:last").prettyPhoto({
		    custom_markup: '<div id="bsap_1237859" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6" style="height:260px"></div><div id="bsap_1251710" class="bsarocks bsap_d49a0984d0f377271ccbf01a33f2b6d6"></div>',
		    changepicturecallback: function(){ _bsap.exec(); }
	    });
    });
    </script>

</body>
</html>